version: '3.7'
services:
  dirlister:
    restart: always
    build:
      context: .
      dockerfile: docker/dirlister.Dockerfile
    image: inveracity/dirlister:latest
    container_name: dirlister
    command: gunicorn -b 0.0.0.0:8000 --timeout 600 app:app
    network_mode: host
    ports:
      - "8000:8000"
    environment:
      DIRLISTER_TARGET: /data # keep same as target
    volumes:
      - type: bind
        source: /mnt # The data on your computer
        target: /data # the folder in the container

      ## Uncomment this to load a custom filter
      #- type: bind
      #  source: ./filter.yaml
      #  target: /dirlister/filter.yaml
